apiVersion: v1
kind: Service
metadata:
  name: login-app-service
  labels:
    name: login-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
  selector:
    name: login-app-pod
